version: '3'

services:
  database:
    image: mongo
    logging:
      driver: none
  database-ui:
    image: mongo-express
    logging:
      driver: none
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
    - 15001:8081
  api:
    build:
      context: .
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://database
      AUTHORIZATION_KEY: test
    ports:
    - 15000:8080