version: '3'

services:
  database:
    image: mongo
    logging:
      driver: none
  database-ui:
    image: mongo-express
    logging:
      driver: none
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    ports:
      - 15001:8081
  api:
    image: creekorful/quotes-api
    restart: unless-stopped
    environment:
      DB_URI: mongodb://database
      LOG_LVL: DEBUG
      AUTHORIZATION_KEY: test
    ports:
      - 15000:8080